config/routes.rb
Rails.application.routes.draw do
  root to: "projects/projects#index"

  namespace :projects do
    resources :projects
  end
end

app/models/application_model.rb
require 'types'

class ApplicationModel < ROM::Struct
  def self.inherited(klass)
    super

    klass.extend ActiveModel::Naming
    klass.include ActiveModel::Conversion

    klass.constructor_type :schema

    klass.attribute :id, Types::Strict::Int.optional.meta(primary_key: true)
  end

  def persisted?
    id.present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationModel
  attribute :name, Types::Strict::String
  attribute :tickets, Types::Strict::Array.of(Ticket).default([])

  def contributors
    tickets.map(&:user).uniq
  end
end

app/models/projects/project.rb
module Projects
  class Project < ApplicationModel
    attribute :name, Types::Strict::String
  end
end

app/models/projects/ticket.rb
module Projects
  class Ticket < ApplicationModel
    attribute :title, Types::Strict::String
    attribute :comment, Types::Strict::String
    attribute :project_id, Types::Strict::Int
    attribute :user_id, Types::Strict::Int
  end
end

app/models/ticket.rb
class Ticket < ApplicationModel
  attribute :title, Types::Strict::String
  attribute :comment, Types::Strict::String
  attribute :project_id, Types::Strict::Int
  attribute :user_id, Types::Strict::Int
  attribute :user, Types::Constructor(User)
end

app/models/user.rb
class User < ApplicationModel
  attribute :username, Types::Strict::String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects/projects_controller.rb
module Projects
  class ProjectsController < ApplicationController
    def index
      @projects = repo.all
    end

    def show
      @project = repo.by_id(params[:id])
    end

    def new
      @project = Projects::Project.new
    end

    def create
      transaction = Projects::Create.new
      transaction.(project_params) do |result|
        result.success do |project|
          flash[:notice] = "Project has been created."
          redirect_to project
        end

        result.failure :validate do |errors|
          @project = Projects::Project.new(project_params)
          @errors = errors
          flash[:alert] = "Project could not be created."
          render :new
        end
      end
    end

    private

    def project_params
      params.require(:projects_project).permit(:name).to_h.symbolize_keys
    end

    def repo
      ProjectRepository.new(rom)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = repo.all
  end

  def show
    @project = repo.by_id_with_tickets_and_users(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    transaction = CreateProject.new
    transaction.(project_params) do |result|
      result.success do |project|
        flash[:notice] = "Project has been created."
        redirect_to project
      end

      result.failure :validate do |errors|
        @project = Project.new(project_params)
        @errors = errors
        flash[:alert] = "Project could not be created."
        render :new
      end
    end
end

  private

  def project_params
    params.require(:project).permit(:name).to_h.symbolize_keys
  end

  def repo
    ProjectRepository.new(ROM.env)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<h2>Projects</h2>

<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= form_with(model: @project, local: true) do |form| %>
  <%= render "shared/error_messages", errors: @errors %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </p>

  <%= form.submit %>
<% end %>

app/views/projects/projects/index.html.erb
<h2>Projects</h2>

<%= link_to "New Project", new_projects_project_path, class: "btn btn-primary" %>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/projects/new.html.erb
<h2>New Project</h2>

<%= form_with(model: @project, local: true) do |form| %>
  <%= render "shared/error_messages", errors: @errors %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <%= form.submit %>
<% end %>

app/views/projects/projects/show.html.erb
<h2><%= @project.name %></h2>

app/views/shared/_error_messages.html.erb
<% if errors.present? %>
  <p>
    There were errors that prevented this form from being saved:
  </p>

  <ul>
    <% errors.map do |key, messages| %>
      <% messages.each do |error| %>
        <li><%= key.to_s.capitalize %> <%= error %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>